# Generated by Django 3.0.6 on 2020-06-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_student_comment2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='comment2',
        ),
    ]
