# Generated by Django 3.0.6 on 2020-11-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_auto_20201108_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment3',
            field=models.CharField(default='available', max_length=40),
        ),
    ]
