# Generated by Django 3.0.6 on 2020-11-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_student_comment3'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default='not available'),
        ),
        migrations.AlterField(
            model_name='student',
            name='comment3',
            field=models.CharField(max_length=40),
        ),
    ]
