# Generated by Django 3.0.6 on 2020-11-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_auto_20201108_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
