# Generated by Django 3.0.6 on 2020-11-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_auto_20201108_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.AddField(
            model_name='student',
            name='date2',
            field=models.DateField(auto_now=True),
        ),
    ]
