# Generated by Django 3.0.6 on 2020-11-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_auto_20201109_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date2',
        ),
    ]
