# Generated by Django 3.0.6 on 2020-11-09 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_remove_student_date2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 9, 4, 6, 22, 470299, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
