from django import forms
class StudentRegistration(forms.Form):
    #name = forms.CharField(min_length=5, max_length=10)
    #name = forms.CharField(min_length=5, max_length=10,strip=False)
    #name = forms.CharField(empty_value='Nitish')
    name = forms.CharField(error_messages={'required':'Enter Your Name'})
    roll = forms.IntegerField(min_value=5, max_value=30)
    price = forms.DecimalField(min_value=5, max_value=30, max_digits=4, decimal_places=2)
    rate = forms.FloatField(min_value=5, max_value=30)
    comment = forms.SlugField()
    email = forms.EmailField(min_length=5, max_length=30, widget=forms.EmailInput)
    website = forms.URLField(min_length=5, max_length=30)
    password = forms.CharField(min_length=5, max_length=30, widget=forms.PasswordInput)
    description = forms.CharField(widget=forms.Textarea)
    feedback = forms.CharField(min_length=5, max_length=30, widget=forms.TextInput(attrs={'class':'somecss1 somecss2','id':'uniquied'}))
    notes = forms.CharField(widget=forms.Textarea(attrs={'rows':3,'cols':50}))
    agree = forms.BooleanField(label='I Agree', label_suffix=' ')